import type { Icon } from "@phosphor-icons/react";
import {
  GraduationCap,
  ChalkboardTeacher,
  BookOpen,
  Books,
  Student,
  Lightbulb,
  Users,
  UsersThree,
  Heart,
  Star,
  StarHalf,
  Clock,
  CalendarBlank,
  CalendarCheck,
  ChatCircle,
  Check,
  CheckCircle,
  ArrowRight,
  CaretRight,
  List,
  X,
  Plus,
  Minus,
  MagnifyingGlass,
  Envelope,
  Phone,
  MapPin,
  Play,
  Quotes,
  Certificate,
  Medal,
  Smiley,
  PuzzlePiece,
  Palette,
  Image,
  User,
  Sparkle,
  PencilSimple,
  HandHeart,
} from "@phosphor-icons/react";

/** The Phosphor icons used across the Armstrong system (regular weight). */
export const systemIcons: { name: string; Icon: Icon }[] = [
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "ChalkboardTeacher", Icon: ChalkboardTeacher },
  { name: "BookOpen", Icon: BookOpen },
  { name: "Books", Icon: Books },
  { name: "Student", Icon: Student },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Users", Icon: Users },
  { name: "UsersThree", Icon: UsersThree },
  { name: "Heart", Icon: Heart },
  { name: "Star", Icon: Star },
  { name: "StarHalf", Icon: StarHalf },
  { name: "Clock", Icon: Clock },
  { name: "CalendarBlank", Icon: CalendarBlank },
  { name: "CalendarCheck", Icon: CalendarCheck },
  { name: "ChatCircle", Icon: ChatCircle },
  { name: "Check", Icon: Check },
  { name: "CheckCircle", Icon: CheckCircle },
  { name: "ArrowRight", Icon: ArrowRight },
  { name: "CaretRight", Icon: CaretRight },
  { name: "List", Icon: List },
  { name: "X", Icon: X },
  { name: "Plus", Icon: Plus },
  { name: "Minus", Icon: Minus },
  { name: "MagnifyingGlass", Icon: MagnifyingGlass },
  { name: "Envelope", Icon: Envelope },
  { name: "Phone", Icon: Phone },
  { name: "MapPin", Icon: MapPin },
  { name: "Play", Icon: Play },
  { name: "Quotes", Icon: Quotes },
  { name: "Certificate", Icon: Certificate },
  { name: "Medal", Icon: Medal },
  { name: "Smiley", Icon: Smiley },
  { name: "PuzzlePiece", Icon: PuzzlePiece },
  { name: "Palette", Icon: Palette },
  { name: "Image", Icon: Image },
  { name: "User", Icon: User },
  { name: "Sparkle", Icon: Sparkle },
  { name: "PencilSimple", Icon: PencilSimple },
  { name: "HandHeart", Icon: HandHeart },
];
